site: "Speechwriting Practice"
baseurl: "speechwriting"
url: https://joshuafayer.com/
permalink: /:title/
sass:
  style: expanded
collections:
  posts:
    output: true
    permalink: /sessions/:title
plugins:
  - jekyll-sitemap
